assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", include("contacts.urls")),
    path("docs/", include("docs.urls")),
    path("", include("news.urls")),
    path("notes/", include("notes.urls")),
    path("users/", include("users.urls")),
]

assistant/contacts/urls.py
from django.urls import path
from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.contact_list, name="contact_list"),
    path("add/", views.add_contact, name="add_contact"),
    path("<int:contact_id>/edit/", views.edit_contact, name="edit_contact"),
    path("<int:contact_id>/delete/", views.delete_contact, name="delete_contact"),
    path("search/", views.search_contacts, name="search_contacts"),
    path("upcoming_birthdays/", views.upcoming_birthdays, name="upcoming_birthdays"),
]

assistant/docs/urls.py
from django.urls import path
from . import views

app_name = "docs"

urlpatterns = [
    path("user_files/", views.user_files, name="user_files"),
    path("rename/", views.rename_file, name="rename_file"),
    path("delete/", views.delete_file, name="delete_file"),
]

assistant/contacts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    thurname = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    birthdate = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=False)
    created_date = models.DateTimeField(auto_now_add=True)

assistant/contacts/forms.py
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import (
    ModelForm,
    CharField,
    EmailField,
    DateField,
    DateInput,
    TextInput,
)
from .models import Contact
from phonenumber_field.formfields import PhoneNumberField


class ContactForm(ModelForm):
    name = CharField(
        max_length=20,
        required=True,
        widget=TextInput(attrs={"placeholder": "obligatory field"}),
    )
    thurname = CharField(max_length=20, required=False)
    address = CharField(max_length=100, required=False)
    phone = PhoneNumberField(
        required=False,
        widget=TextInput(attrs={"placeholder": "ex. +4402031234567"}),
    )
    email = EmailField(max_length=50, required=False)
    birthdate = DateField(
        required=False,
        widget=DateInput(attrs={"type": "date"}),
    )

    class Meta:
        model = Contact
        fields = (
            "name",
            "thurname",
            "address",
            "phone",
            "email",
            "birthdate",
        )

    def clean_birthdate(self):
        """
        The clean_birthdate function is a custom validation function that checks if the birthdate entered by the user is valid.
            It first gets the data from cleaned_data dictionary and then checks if it's not None. If it's not None, then we check
            whether or not it's in future or older than 100 years old. If any of these conditions are met, we raise an error.

        :param self: Access the instance of the class
        :return: A date object
        :doc-author: Trelent
        """
        data = self.cleaned_data.get("birthdate")
        print(data)
        today = date.today()
        if data is not None:
            if data > today:
                raise ValidationError("Birthdate cannot be in future")
            elif (today - data).days > (365 * 100):
                raise ValueError("User cannot be older than 100 years")
            return data

assistant/contacts/views.py
from datetime import date

from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .forms import ContactForm
from .models import Contact


@login_required
def contact_list(request):
    """
    The contact_list function is responsible for rendering the contact_list.html template,
    which displays all of the contacts in a user's address book.

    :param request: Pass the request object to the view
    :return: A rendered template
    :doc-author: Trelent
    """
    contacts = Contact.objects.filter(user=request.user).order_by("name", "thurname")
    return render(request, "contacts/contact_list.html", {"contacts": contacts})


@login_required
def add_contact(request):
    """
    The add_contact function is a view that allows users to add contacts.
        It takes in the request and returns a rendered template with the form.
        If the form is valid, it saves it to the database and redirects to contact_list.

    :param request: Get the current request
    :return: The rendered template of the form if it is not valid
    :doc-author: Trelent
    """
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect("contacts:contact_list")
    else:
        form = ContactForm()
    return render(request, "contacts/add_contact.html", {"form": form})


@login_required
def edit_contact(request, contact_id):
    """
    The edit_contact function is used to edit an existing contact.
        It takes a request and a contact_id as arguments, and returns the rendered template for editing contacts.


    :param request: Get the current request
    :param contact_id: Get the contact object from the database
    :return: A render function
    :doc-author: Trelent
    """
    contact = get_object_or_404(Contact, pk=contact_id, user=request.user)
    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect("contacts:contact_list")
    else:
        form = ContactForm(instance=contact)

    return render(
        request, "contacts/edit_contact.html", {"form": form, "contact": contact}
    )


@login_required
def delete_contact(request, contact_id):
    """
    The delete_contact function is used to delete a contact from the database.
        It takes in a request and contact_id as parameters, and returns either
        an HTML page or redirects to another page depending on the method of the request.


    :param request: Get the request object that is sent to the server
    :param contact_id: Get the contact object from the database
    :return: A render() function, which is the page that will be displayed to the user
    :doc-author: Trelent
    """
    contact = get_object_or_404(Contact, pk=contact_id, user=request.user)
    if request.method == "POST":
        contact.delete()
        return redirect("contacts:contact_list")
    return render(request, "contacts/delete_contact.html", {"contact": contact})


@login_required
def search_contacts(request):
    """
    The search_contacts function is a view that allows users to search for contacts by name, email or phone number.
    The function takes in the request object and returns a rendered template with the results of the query.

    :param request: Get the current request object
    :return: The rendered contact_list
    :doc-author: Trelent
    """
    query = request.GET.get("q")
    if query:
        contacts = Contact.objects.filter(
            Q(name__icontains=query)
            | Q(email__icontains=query)
            | Q(phone__icontains=query),
            user=request.user,
        ).order_by("name", "thurname")
    else:
        contacts = Contact.objects.filter(user=request.user).order_by(
            "name", "thurname"
        )
    return render(
        request, "contacts/contact_list.html", {"contacts": contacts, "query": query}
    )


@login_required
def upcoming_birthdays(request):
    """
    The upcoming_birthdays function takes a request and returns a list of contacts whose birthdays are within the next 7 days.
    The function first gets today's date, then it gets all the contacts that have birthdates and belong to the current user.
    It then loops through each contact, getting their birthday this year (or next year if their birthday has already passed).
    Then it calculates how many days until their birthday is from today's date. If there are less than or equal to 7 days left until
    their birthday, they get added to our result list.

    :param request: Pass the request object to the view
    :return: The contacts that have a birthday in the next 7 days
    :doc-author: Trelent
    """
    today = date.today()
    contacts = Contact.objects.filter(birthdate__isnull=False, user=request.user)

    result = []
    for contact in contacts:
        date_of_birth = contact.birthdate
        date_this_year = date_of_birth.replace(year=today.year)
        if date_this_year < today:
            date_this_year = date_this_year.replace(year=today.year + 1)
        days_to_birthday = (date_this_year - today).days
        if days_to_birthday <= 7:
            result.append(contact)
    return render(request, "contacts/upcoming_birthdays.html", {"contacts": result})

assistant/contacts/templates/contacts/add_contact.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Add Contact" %}</h1>

    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="col-md-8">
            <div class="row mb-3">
                <h6>{% trans "First Name" %}:</h6>
                {{ form.name }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Family Name" %}:</h6>
                {{ form.thurname }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Address" %}:</h6>
                {{ form.address }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Phone" %}:</h6>
                {{ form.phone }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Email" %}:</h6>
                {{ form.email }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Birthdate" %}:</h6>
                {{ form.birthdate }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        <a class="btn btn-secondary" href="{% url 'contacts:contact_list' %}">{% trans "Discard" %}</a>
        </form>
{% endblock %}

assistant/contacts/templates/contacts/contact_list.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Contact List" %}</h1>
    <div class="col-md-8">
        <a href="{% url 'contacts:add_contact' %}" class="btn btn-primary">{% trans "Add New" %}</a>
        <a href="{% url 'contacts:upcoming_birthdays' %}" class="btn btn-info">{% trans "Upcoming Birthdays" %}</a>
    </div>
    <form method="GET" action="{% url 'contacts:search_contacts' %}" class="form-inline my-2">
        <input class="form-control mr-sm-2" type="text" name="q" placeholder="{% trans "Search by name, email or phone" %}" value="{{ query }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
        <a class="btn btn-secondary" href="{% url 'contacts:contact_list' %}">{% trans "Reset" %}</a>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>{% trans "First Name" %}</th>
                <th>{% trans "Family Name" %}</th>
                <th>{% trans "Address" %}</th>
                <th>{% trans "Phone" %}</th>
                <th>{% trans "Email" %}</th>
                <th>{% trans "Birthdate" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
            <tr>
                <td>{{ contact.name }}</td>
                <td>{{ contact.thurname }}</td>
                <td>{{ contact.address }}</td>
                <td>{{ contact.phone }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.birthdate }}</td>
                <td>
                    <a href="{% url 'contacts:edit_contact' contact_id=contact.id %}" class="btn btn-warning btn-sm">{% trans "Edit" %}</a>
                    <a href="{% url 'contacts:delete_contact' contact_id=contact.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

assistant/contacts/templates/contacts/delete_contact.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Delete Contact" %}</h1>
    <p class="mt-4">{% trans "Are you sure you want to delete?" %}</p>
    <p>{% trans "Contact Name" %}: <strong>{{ contact.name }} {{ contact.thurname }}</strong></p>
    
    <form method="post" class="mt-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        <a class="btn btn-secondary" href="{% url 'contacts:contact_list' %}">{% trans "Discard" %}</a>
    </form>
{% endblock %}

assistant/contacts/templates/contacts/edit_contact.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Edit Contact" %}</h1>

    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="col-md-8">
            <div class="row mb-3">
                <h6>{% trans "First Name" %}:</h6>
                {{ form.name }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Family Name" %}:</h6>
                {{ form.thurname }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Address" %}:</h6>
                {{ form.address }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Phone" %}:</h6>
                {{ form.phone }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Email" %}:</h6>
                {{ form.email }}
            </div>
            <div class="row mb-3">
                <h6>{% trans "Birthdate" %}:</h6>
                {{ form.birthdate }}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        <a class="btn btn-secondary" href="{% url 'contacts:contact_list' %}">{% trans "Discard" %}</a>
    </form>
{% endblock %}

assistant/contacts/templates/contacts/upcoming_birthdays.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <h1 class="mt-4">{% trans "Upcoming Birthdays" %}</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>{% trans "First Name" %}</th>
                <th>{% trans "Family Name" %}</th>
                <th>{% trans "Address" %}</th>
                <th>{% trans "Phone" %}</th>
                <th>{% trans "Email" %}</th>
                <th>{% trans "Birthdate" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
            <tr>
                <td>{{ contact.name }}</td>
                <td>{{ contact.thurname }}</td>
                <td>{{ contact.address }}</td>
                <td>{{ contact.phone }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.birthdate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Links -->
    <div class="col-md-8">
        <a class="btn btn-secondary" href="{% url 'contacts:contact_list' %}">{% trans "Back" %}</a>
    </div>
{% endblock %}