assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", include("contacts.urls")),
    path("docs/", include("docs.urls")),
    path("", include("news.urls")),
    path("notes/", include("notes.urls")),
    path("users/", include("users.urls")),
]

assistant/docs/urls.py
from django.urls import path
from . import views

app_name = "docs"

urlpatterns = [
    path("user_files/", views.user_files, name="user_files"),
    path("rename/", views.rename_file, name="rename_file"),
    path("delete/", views.delete_file, name="delete_file"),
]

assistant/notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.note_list, name="note_list"),
    path("create/", views.create_note, name="create_note"),
    path("search/", views.search_note, name="search_note"),
    path("<int:pk>/edit/", views.edit_note, name="edit_note"),
    path("<int:pk>/delete/", views.delete_note, name="delete_note"),
]

assistant/notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    tags = models.CharField(max_length=255)

    def __str__(self):
        return self.text

assistant/notes/forms.py
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):
    tags = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Tag_1, Tag_2, Tag_3"}),
    )

    class Meta:
        model = Note
        fields = ["text", "tags"]

    def clean_tags(self):
        """
        The clean_tags function takes the tags field from the form and splits it into a list of strings.
        It then iterates through each string in that list, adding a comma to any string that doesn't already have one.
        Finally, it joins all but the last item in the list with spaces between them and adds back on to this joined string
        the last item in tag_list without its trailing comma.

        :param self: Access the instance of the class
        :return: A string with all the tags separated by a space
        :doc-author: Trelent
        """
        tags = self.cleaned_data["tags"]

        tag_list = [tag.strip() for tag in tags.split()]

        for index, tag in enumerate(tag_list):
            if "," not in tag:
                tag_list[index] = f"{tag},"

        cleaned_tags = " ".join(tag_list[:-1])
        cleaned_tags += f' {tag_list[-1].strip(",")}'
        return cleaned_tags

assistant/notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Note
from .forms import NoteForm


@login_required
def note_list(request):
    """
    The note_list function is a view that displays all notes in the database.
    It also counts how many times each tag appears and sorts them by count.

    :param request: Get the current user
    :return: A template with the notes and tags_count variables
    :doc-author: Trelent
    """
    notes = Note.objects.filter(user=request.user).order_by("tags", "text")
    for note in notes:
        note.tags_list = note.tags.split(",")
    all_tags = set(tag for note in notes for tag in note.tags.split(","))
    tags_count = {
        tag: sum(1 for note in notes if tag in note.tags.split(",")) for tag in all_tags
    }
    sorted_tags_count = {tag: count for tag, count in sorted(tags_count.items())}
    return render(
        request,
        "notes/note_list.html",
        {"notes": notes, "tags_count": sorted_tags_count},
    )


@login_required
def create_note(request):
    """
    The create_note function is a view that allows users to create notes.
        It takes in the request and returns a rendered template with the form for creating notes.
        If the user submits data via POST, it will validate that data and save it to the database.

    :param request: Get the request from the user
    :return: A redirect to the note_list view if the form is valid
    :doc-author: Trelent
    """
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            note.save()
            return redirect("notes:note_list")
    else:
        form = NoteForm()
    return render(request, "notes/create_note.html", {"form": form})


@login_required
def edit_note(request, pk):
    """
    The edit_note function takes a request and primary key as arguments.
    It gets the note object from the database using get_object_or_404, which returns an error if it can't find a note with that pk.
    The function then checks whether the request is POST or GET, and if it's POST, saves any changes to the form instance (the edited note).
    If not, it creates an empty form instance for editing.

    :param request: Get the request object
    :param pk: Get the note that we want to delete
    :return: A redirect to the note_list view
    :doc-author: Trelent
    """
    note = get_object_or_404(Note, pk=pk, user=request.user)
    if request.method == "POST":
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect("notes:note_list")
    else:
        form = NoteForm(instance=note)
    return render(request, "notes/edit_note.html", {"form": form, "note": note})


@login_required
def delete_note(request, pk):
    """
    The delete_note function is used to delete a note.
        It takes in the request and pk as parameters, gets the note object or returns 404 if it doesn't exist,
        then checks if the request method is POST. If so, it deletes the note and redirects to notes:note_list.
        Otherwise, it renders a template with &quot;note&quot; as context.

    :param request: Get the request object
    :param pk: Get the note that is going to be deleted
    :return: The delete_note
    :doc-author: Trelent
    """
    note = get_object_or_404(Note, pk=pk, user=request.user)
    if request.method == "POST":
        note.delete()
        return redirect("notes:note_list")
    return render(request, "notes/delete_note.html", {"note": note})


@login_required
def search_note(request):
    """
    The search_note function takes a request object as an argument.
    The function then gets the query from the request object and checks if it is empty. If it is,
    the user will be redirected to the note_list page. The cleaned_query variable removes any commas or periods
    from the query string and strips any whitespace from both ends of that string. The tags variable splits up
    the cleaned_query into a list of strings based on spaces in between words in that string (e.g., &quot;hello world&quot; would become [&quot;hello&quot;, &quot;world&quot;]). If there are no tags, then we redirect to note

    :param request: Get the request object
    :return: The note_list
    :doc-author: Trelent
    """
    query = request.GET.get("q")
    if not query:
        return redirect("notes:note_list")
    cleaned_query = query.replace(",", "").replace(".", "").strip()

    tags = cleaned_query.split()

    if not tags:
        return redirect("notes:note_list")

    q_objects = Q()
    for tag in tags:
        q_objects |= Q(tags__icontains=tag)

    notes = Note.objects.filter(user=request.user).filter(q_objects)

    for note in notes:
        note.tags_list = note.tags.split(",")

    all_tags = set(tag for note in notes for tag in note.tags.split(","))
    tags_count = {
        tag: sum(1 for note in notes if tag in note.tags.split(",")) for tag in all_tags
    }
    sorted_tags_count = {tag: count for tag, count in sorted(tags_count.items())}
    context = {
        "notes": notes,
        "query": query,
        "tags_count": sorted_tags_count,
    }

    return render(request, "notes/note_list.html", context)

assistant/notes/templates/notes/create_note.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <h6>{% trans "Content" %}:</h6>
                            {{ form.text }}
                        </div>
                        <div class="col-md-6 mb-3">
                            <h6>{% trans "Tags" %}:</h6>
                            {{ form.tags }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                    <a href="{% url 'notes:note_list' %}" class="btn btn-secondary">{% trans "Discard" %}</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

assistant/notes/templates/notes/delete_note.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-danger text-white">
                        {% trans "Delete Note" %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{% trans "Are you sure you want to delete this note?" %}</h5>
                        <p class="card-text">{{ note.text }} - {{ note.tags }}</p>
                        
                        <form method="post" class="mt-4">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                            <a href="{% url 'notes:note_list' %}" class="btn btn-secondary">{% trans "Cancel and Back to Note List" %}</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

assistant/notes/templates/notes/edit_note.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="mb-4">{% trans "Edit Note" %}</h2>
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <h6>{% trans "Content" %}:</h6>
                            {{ form.text }}
                        </div>
                        <div class="col-md-6 mb-3">
                            <h6>{% trans "Tags" %}:</h6>
                            {{ form.tags }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                    <a href="{% url 'notes:note_list' %}" class="btn btn-secondary">{% trans "Discard" %}</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

assistant/notes/templates/notes/note_list.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
    <div class="container mt-1">
        <div class="row">
            <div class="col-md-8">
                <a href="{% url 'notes:create_note' %}" class="btn btn-primary btn-block mb-4">{% trans "Create New Note" %}</a>
                
                <form method="get" action="{% url 'notes:search_note' %}" class="mb-3">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="{% trans 'Search by tags' %}" value="{{ query }}">
                        <button type="submit" class="btn btn-primary">{% trans "Search" %}</button>
                    </div>
                </form>

                {% for note in notes %}
                    <div class="card mb-3">
                        <div class="card-body">
                            {{ note.text }}
                            <div class="mt-3">
                                {% for tag in note.tags_list %}
                                    <a href="{% url 'notes:search_note' %}?q={{ tag|urlencode }}" class="badge bg-secondary me-1">{{ tag }}</a>
                                {% endfor %}

                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'notes:edit_note' pk=note.pk %}" class="btn btn-sm btn-warning">{% trans "Edit" %}</a>
                            <a href="{% url 'notes:delete_note' pk=note.pk %}" class="btn btn-sm btn-danger">{% trans "Delete" %}</a>
                        </div>
                    </div>
                {% empty %}
                    <p>{% trans "No notes available." %}</p>
                {% endfor %}

                <div class="mb-3">
                    {% if query %}
                        <a href="{% url 'notes:note_list' %}" class="btn btn-secondary">{% trans "Back to Note List" %}</a>
                    {% endif %}
                </div>
            </div>

            {% if tags_count %}
            <div class="col-md-4">
                <ul class="list-group mb-4">
                    {% for tag, count in tags_count.items %}
                        <!-- tag -->
                        <a href="{% url 'notes:search_note' %}?q={{ tag }}" class="text-decoration-none text-dark">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ tag }}
                                <span class="badge bg-primary rounded-pill">{{ count }}</span>
                            </li>
                        </a>
                        
                        <!-- tag -->
                    {% endfor %}
                </ul>

                <!-- News Widget -->
                <div class="news-widget">
                    <h3>{% trans "Latest News" %}</h3>
                    <ul>
                    {% for news_item in latest_news %}
                        <li>
                            <a href="{{ news_item.url }}">{{ news_item.title }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                <!-- End of News Widget -->
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}