assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", include("contacts.urls")),
    path("docs/", include("docs.urls")),
    path("", include("news.urls")),
    path("notes/", include("notes.urls")),
    path("users/", include("users.urls")),
]

assistant/docs/urls.py
from django.urls import path
from . import views

app_name = "docs"

urlpatterns = [
    path("user_files/", views.user_files, name="user_files"),
    path("rename/", views.rename_file, name="rename_file"),
    path("delete/", views.delete_file, name="delete_file"),
]

assistant/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

assistant/users/models.py
from django.db import models

# Create your models here.

assistant/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(
        max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"})
    )
    first_name = CharField(
        max_length=150,
        required=False,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    last_name = CharField(
        max_length=150,
        required=False,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    email = EmailField(
        max_length=150,
        required=True,
        widget=EmailInput(attrs={"class": "form-control"}),
    )
    password1 = CharField(
        max_length=12,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )
    password2 = CharField(
        max_length=12,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"})
    )
    password = CharField(
        max_length=12,
        min_length=8,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = ("username", "password")

assistant/users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        """
        The dispatch function is the first function that gets called when a request
        is made to this view. It's job is to decide what type of request it is, and then
        call the appropriate method for handling that request. For example, if you make an HTTP GET
        request to /accounts/register/, dispatch will call get() because it knows that an HTTP GET
        request should be handled by a get() method.

        :param self: Represent the instance of the class
        :param request: Get the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: A redirect to the news:root page if a user is authenticated
        :doc-author: Trelent
        """
        if request.user.is_authenticated:
            return redirect(to="news:root")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        """
        The get function renders the form to the user.


        :param self: Represent the instance of the class
        :param request: Get the request object
        :return: The form
        :doc-author: Trelent
        """
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        """
        The post function is used to create a new user.
            It takes the request as an argument and returns a redirect to the login page if successful, or renders the signup template with form errors otherwise.

        :param self: Represent the instance of the class
        :param request: Pass the request object to the view
        :return: A render function, which is a response object
        :doc-author: Trelent
        """
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(
                request,
                f"Congratulations {username}. Your account is successfully created",
            )
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

assistant/users/templates/users/login.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "Login" %}</h1>

<!-- Display flash notification -->
<!-- {% if messages %} -->
<!-- {% for message in messages %} -->
<!-- <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert"> -->
  <!-- {{message}} -->
<!-- </div> -->
<!-- {% endfor %} -->
<!-- {% endif %} -->

<!-- Processing form errors that do not relate to fields -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
{% endif %}

<form method="post">
  {% csrf_token %}
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Username" %}</label>
      {{form.username}}
    </div>
    <span>{{form.errors.username}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Password" %}</label>
      {{form.password}}
    </div>
    <span>{{form.errors.password}}</span>
  </div>
  <button type="submit" class="btn btn-primary">{% trans "Log In" %}</button>
  <div class="small text-center">
    <a href="{% url 'users:password_reset' %}" class="text-center"><i>{% trans "Forgot Password?" %}</i></a>
  </div>
</form>
{% endblock %}

assistant/users/templates/users/logout.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "See you later" %}</h1>
{% endblock %}

assistant/users/templates/users/password_reset.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}

<h2>{% trans "Password reset" %}</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">{% trans "Request password reset" %}</button>
</form>

{% endblock %}

assistant/users/templates/users/password_reset_complete.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}
<h2>{% trans "Password reset complete!" %}</h2>
{% endblock %}

assistant/users/templates/users/password_reset_confirm.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}

<h2>{% trans "Enter new password" %}</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">{% trans "Save new password" %}</button>
</form>

{% endblock %}

assistant/users/templates/users/password_reset_done.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}

<h2>{% trans "Password reset request sent" %}</h2>
<p>
  {% trans "Shortly you will receive an email with instructions to reset your password" %}
</p>

{% endblock %}

assistant/users/templates/users/password_reset_email.html
{% autoescape off %}
{% load i18n %}

<body>
  <p>{% trans "Hi" %} {{ user.username }},</p>
  <p>
    {% trans "You requested a password reset for your account. Please follow this link to set a new password:" %}
  </p>
  <p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
      {% trans "Reset password" %}
    </a>
  </p>
  <p>{% trans "If you didn't request a password reset, please ignore this email." %}</p>
  <p>{% trans "Sincerely Yours," %}</p>
  <p>{% trans "Your Hangover Team" %}</p>
</body>

{% endautoescape %}

assistant/users/templates/users/signup.html
{% extends "news/base.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "SignUp" %}</h1>
<form method="post">
  {% csrf_token %}
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Username" %}</label>
      {{form.username}}
    </div>
    <span>{{form.errors.username}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "First Name" %}</label>
      {{form.first_name}}
    </div>
    <span>{{form.errors.first_name}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Last Name" %}</label>
      {{form.last_name}}
    </div>
    <span>{{form.errors.last_name}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Email" %}</label>
      {{form.email}}
    </div>
    <span>{{form.errors.email}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Password" %}</label>
      {{form.password1}}
    </div>
    <span>{{form.errors.password1}}</span>
  </div>
  <div class="form-row">
    <div class="mb-3">
      <label class="form-label">{% trans "Confirm password" %}</label>
      {{form.password2}}
    </div>
    <span>{{form.errors.password2}}</span>
  </div>
  <button type="submit" class="btn btn-primary">{% trans "Sign Up" %}</button>
</form>
{% endblock %}