assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", include("contacts.urls")),
    path("docs/", include("docs.urls")),
    path("", include("news.urls")),
    path("notes/", include("notes.urls")),
    path("users/", include("users.urls")),
]

assistant/contacts/urls.py
from django.urls import path
from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.contact_list, name="contact_list"),
    path("add/", views.add_contact, name="add_contact"),
    path("<int:contact_id>/edit/", views.edit_contact, name="edit_contact"),
    path("<int:contact_id>/delete/", views.delete_contact, name="delete_contact"),
    path("search/", views.search_contacts, name="search_contacts"),
    path("upcoming_birthdays/", views.upcoming_birthdays, name="upcoming_birthdays"),
]

assistant/docs/urls.py
from django.urls import path
from . import views

app_name = "docs"

urlpatterns = [
    path("user_files/", views.user_files, name="user_files"),
    path("rename/", views.rename_file, name="rename_file"),
    path("delete/", views.delete_file, name="delete_file"),
]

assistant/news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.news_list, name="root"),
    path("index/", views.main, name="index"),
    path("news/", views.news_list, name="news_list"),
    path("news_ua/<str:topic>/", views.news_list_ua, name="news_ua_topic"),
    path("news/<str:category>/", views.news_list, name="news_list_category"),
]

assistant/notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
    path("", views.note_list, name="note_list"),
    path("create/", views.create_note, name="create_note"),
    path("search/", views.search_note, name="search_note"),
    path("<int:pk>/edit/", views.edit_note, name="edit_note"),
    path("<int:pk>/delete/", views.delete_note, name="delete_note"),
]

assistant/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

assistant/news/models.py
from django.db import models

class News(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    url = models.URLField()
    topic = models.CharField()
    date = models.CharField()

assistant/news/views.py
from datetime import datetime
from django.shortcuts import render
import requests
from django.conf import settings
import json
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import News
from .scrap_news import articles_scraped
import time


def main(request):
    """
    The main function is the entry point for the news app.
    It renders a template called index.html, which displays all of the articles in our database.

    :param request: Get the request object that is sent to the view
    :return: The template index
    :doc-author: Trelent
    """
    return render(request, "news/index.html", {})


CATEGORIES = [
    ("main", "Головні"),
    ("war", "Війна"),
    ("world", "Світові"),
    ("society", "України"),
    ("economics", "Економіка"),
    ("science", "Наука"),
    ("sport", "Спорт"),
]

NEWSAPI_CATEGORIES = [
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
]


def parse_date(iso_date):
    """
    The parse_date function takes a string in ISO 8601 format and returns a datetime object.

    :param iso_date: Pass the date string to the function
    :return: A datetime object
    :doc-author: Trelent
    """
    return datetime.fromisoformat(iso_date.replace("Z", "+00:00"))


def get_news(category="general"):
    """
    The get_news function takes in a category as an argument and returns the top headlines from that category.
    The default value for the category is &quot;general&quot;.

    :param category: Specify the category of news you want to get
    :return: A list of dictionaries
    :doc-author: Trelent
    """
    url = "https://newsapi.org/v2/top-headlines"
    parameters = {
        "country": "us",
        "category": category,
        "apiKey": settings.NEWSAPI_KEY,
    }
    response = requests.get(url, params=parameters)
    data = response.json()
    return data["articles"]


def news_list(request, category="general"):
    """
    The news_list function is responsible for rendering the news_list.html template,
    which displays a list of news articles from the News API. The function takes in an optional
    category parameter which specifies what category of news to display (e.g., business, entertainment).
    If no category is specified, then it defaults to &quot;general&quot;.

    :param request: Pass the request object to the view
    :param category: Filter the news by category
    :return: A rendered template
    :doc-author: Trelent
    """
    lang = request.session.get(settings.LANGUAGE_SESSION_KEY, "en")
    if lang == "uk":
        return HttpResponseRedirect(
            reverse("news:news_ua_topic", args=("main",)) + "?lang=uk"
        )

    news_data = get_news(category)
    for item in news_data:
        item["publishedAt"] = parse_date(item["publishedAt"]).strftime(
            "%d %B, %Y %H:%M"
        )
    context = {
        "news": news_data,
        "categories": NEWSAPI_CATEGORIES,
        "current_category": category,
    }
    return render(request, "news/news_list.html", context)


def news_list_ua(request, topic="main"):
    """
    The news_list_ua function is a view that displays the news in Ukrainian.
    It takes one argument, request, and returns an HttpResponseRedirect object if the language of the session is English.
    Otherwise it opens data.json file with UTF-8 encoding and loads its content into list_news variable as a dictionary object.
    Then it creates context dictionary with three keys: 'news', 'categories' and 'topic'. The value of each key depends on its name:
    the value for key &quot;news&quot; is equal to list_news[topic], where topic = &quot;main&quot; by default;
    the value for

    :param request: Get the request object
    :param topic: Select news from a specific category
    :return: The news_ua
    :doc-author: Trelent
    """
    lang = request.session.get(settings.LANGUAGE_SESSION_KEY, "en")
    if lang == "en":
        return HttpResponseRedirect(reverse("news:news_list") + "?lang=en")   
    
    news_data = News.objects.filter(topic=topic)
    
    # If there are no news for the selected topic in the database, scrape them
    if not news_data.exists():
        fill_news()
        news_data = News.objects.filter(topic=topic)
  
    context = {"news": news_data, "categories": CATEGORIES, "topic": topic}
    
    return render(request, "news/news_ua.html", context)


def fetch_news(lang="en"):
    """
    The fetch_news function fetches the latest news from the NewsAPI.
        Args:
            lang (str): The language of the news to be fetched. Defaults to English ('en').
        Returns:
            list[dict]: A list of dictionaries containing information about each article, including title, description and url.

    :param lang: Specify the language of news
    :return: A list of dictionaries
    :doc-author: Trelent
    """
    if lang == "en":
        url = (
            "https://newsapi.org/v2/top-headlines?country=us&apiKey="
            + settings.NEWSAPI_KEY
        )
        response = requests.get(url)
        if response.status_code == 200:
            return response.json().get("articles", [])[:5]  # Limit news quantity to 5
        return []
    else:  # Ukrainian
        list_news = News.objects.filter(topic="main")
        # Return only 5 Ukrainian main news from database, you can adapt this part if necessary
        return list_news[:5]
    

def fill_news():  
    """
    The fill_news function allows users to create news and save them to the database.
    
    :doc-author: Trelent
    """
    news_data = articles_scraped()
    # with open("./data.json", "r", encoding="utf-8") as fl:
    #     news_data = json.load(fl)
    for key, value in news_data.items():        
        for el in value:
            News.objects.update_or_create(
                title = el['title'],
                content =el['content'],
                url = el['url'],
                date = el['date'],
                topic = key
                )    


    

assistant/news/templates/news/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'news/style.css' %}" />
    <link rel="icon" href="{% static 'news/favicon.ico' %}"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
      <div class="container">
        <a class="navbar-brand" href="{% url 'news:index' %}?lang={{ request.GET.lang }}">{% trans "Hello World!" %}</a>
        <div class="currency-data ml-3">
            {% if currency_data %}
                {% for key, value in currency_data.items %}
                    <span class="mr-2">{{ key }}: {{ value }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'news:news_list' %}?lang={{ request.GET.lang }}">{% trans "News" %}</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'docs:user_files' %}?lang={{ request.GET.lang }}">{% trans "Files" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts:contact_list' %}?lang={{ request.GET.lang }}">{% trans "Contacts" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'notes:note_list' %}?lang={{ request.GET.lang }}">{% trans "Notes" %}</a>
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
            <!-- Language Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Language" %}
              </a>
              <ul class="dropdown-menu" aria-labelledby="languageDropdown">
                <li><a class="dropdown-item" href="?lang=en">{% trans "English" %}</a></li>
                <li><a class="dropdown-item" href="?lang=uk">{% trans "Українська" %}</a></li>
                <!-- Add more languages as needed -->
              </ul>
            </li>
            <!-- End Language Dropdown -->

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Welcome" %}, {{ user.username }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'news:news_list' %}?lang={{ request.GET.lang }}">{% trans "News" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'docs:user_files' %}?lang={{ request.GET.lang }}">{% trans "Files" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'contacts:contact_list' %}?lang={{ request.GET.lang }}">{% trans "Contacts" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'notes:note_list' %}?lang={{ request.GET.lang }}">{% trans "Notes" %}</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}?lang={{ request.GET.lang }}">{% trans "Logout" %}</a></li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:signup' %}?lang={{ request.GET.lang }}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}?lang={{ request.GET.lang }}">{% trans "Login" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <div class="switch-container d-inline-block ml-2">
          <input type="checkbox" class="switch">
          <div class="lamp">
              <div class="light"></div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">{% block content %} {% endblock %}</div>
    </div>
    <!-- Added Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const switchElement = document.querySelector('.switch');

        // Download the theme from localStorage and apply it
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) {
            document.documentElement.setAttribute('data-bs-theme', savedTheme);
            if (savedTheme === 'light') {
                switchElement.checked = true;
            }
        }

        if (switchElement) {
            switchElement.addEventListener('change', function() {
                if (this.checked) {
                    document.documentElement.setAttribute('data-bs-theme', 'light');
                    localStorage.setItem('theme', 'light');
                } else {
                    document.documentElement.setAttribute('data-bs-theme', 'dark');
                    localStorage.setItem('theme', 'dark');
                }
            });
        }
    });
  </script>
  </body>
</html>

assistant/news/templates/news/index.html
{% extends 'news/base.html'%}
{% load static %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Orbitron&display=swap" rel="stylesheet">
<div class="col-md-8">
    <div class="title-container">
        <h1 class="project-title"></h1>
        <button class="flip-text-btn"></button>
    </div>
    
    <script defer src="{% static 'news/title-animation.js' %}"></script>
</div>
{% endblock %}

assistant/news/templates/news/news_list.html
{% extends "news/base.html" %}
{% load i18n %}

{% block content %}
<div class="container mt-4">
      <div class="d-flex flex-wrap justify-content-between mb-4">
        {% for cat in categories %}
            <div class="card m-2" style="width: 18rem;">
                <a href="{% url 'news:news_list_category' category=cat %}?lang={{ request.GET.lang }}" class="card-link d-flex justify-content-center align-items-center" style="height: 100%;">
                    <h5 class="{% if current_category == cat %}text-primary{% else %}{% endif %}">{{ cat|title }}</h5>
                </a>
            </div>
        {% endfor %}
      </div>
      <div class="list-group">
        {% for item in news %}
        <a href="{{ item.url }}" target="_blank" class="list-group-item list-group-item-action mb-2">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ item.title }}</h5>
                <small>{{ item.publishedAt }}</small>
            </div>
            <p class="mb-1">{{ item.description }}</p>
        </a>
        {% empty %}
        <div class="alert alert-info" role="alert">
            {% trans "No news available." %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

assistant/news/templates/news/news_ua.html
{% extends "news/base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex flex-wrap justify-content-between mb-4">
        {% for category, title in categories %}
            <div class="card m-2" style="width: 18rem;">
                <a href="{% url 'news:news_ua_topic' topic=category %}?lang={{ request.GET.lang }}" class="card-link d-flex justify-content-center align-items-center" style="height: 100%;">
                    <h5 class="{% if topic == category %}text-primary{% else %}{% endif %}">{{ title }}</h5>
                </a>
            </div>
        {% endfor %}
    </div>

    <div class="list-group">
        {% for item in news %}
        <a href="{{ item.url }}" target="_blank" class="list-group-item list-group-item-action mb-2">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ item.title }}</h5>
                <small>{{ item.date }}</small>
            </div>
            <p class="mb-1">{{ item.content }}</p>
        </a>
        {% empty %}
        <div class="alert alert-info" role="alert">
            Новин немає.
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}